version: '2.2'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.2"
    hostname: "elasticsearch"
    container_name: elasticsearchComp
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"